/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAttendanceRouteImport } from './routes/_authenticated/attendance'
import { Route as AuthenticatedBatchesRouteImport } from './routes/_authenticated/batches'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedFeesRouteImport } from './routes/_authenticated/fees'
import { Route as AuthenticatedInvitesRouteImport } from './routes/_authenticated/invites'
import { Route as AuthenticatedPlanRouteImport } from './routes/_authenticated/plan'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedStudentsRouteImport } from './routes/_authenticated/students'
import { Route as JoinTokenRouteImport } from './routes/join.$token'
import { Route as AuthenticatedAdminSubscriptionsRouteImport } from './routes/_authenticated/admin.subscriptions'
import { Route as AuthenticatedReceiptsPaymentIdRouteImport } from './routes/_authenticated/receipts.$paymentId'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings.index'
import { Route as AuthenticatedSettingsTeamRouteImport } from './routes/_authenticated/settings.team'
import { Route as AuthenticatedStudentsIdRouteImport } from './routes/_authenticated/students.$id'
import { Route as ApiBillingStartSubscriptionRouteImport } from './routes/api/billing/start-subscription'
import { Route as ApiBillingSyncSubscriptionRouteImport } from './routes/api/billing/sync-subscription'
import { Route as ApiWebhooksRazorpayRouteImport } from './routes/api/webhooks/razorpay'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAttendanceRoute = AuthenticatedAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBatchesRoute = AuthenticatedBatchesRouteImport.update({
  id: '/batches',
  path: '/batches',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFeesRoute = AuthenticatedFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInvitesRoute = AuthenticatedInvitesRouteImport.update({
  id: '/invites',
  path: '/invites',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlanRoute = AuthenticatedPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStudentsRoute = AuthenticatedStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const JoinTokenRoute = JoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminSubscriptionsRoute =
  AuthenticatedAdminSubscriptionsRouteImport.update({
    id: '/admin/subscriptions',
    path: '/admin/subscriptions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReceiptsPaymentIdRoute =
  AuthenticatedReceiptsPaymentIdRouteImport.update({
    id: '/receipts/$paymentId',
    path: '/receipts/$paymentId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsTeamRoute =
  AuthenticatedSettingsTeamRouteImport.update({
    id: '/team',
    path: '/team',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedStudentsIdRoute = AuthenticatedStudentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedStudentsRoute,
} as any)
const ApiBillingStartSubscriptionRoute =
  ApiBillingStartSubscriptionRouteImport.update({
    id: '/api/billing/start-subscription',
    path: '/api/billing/start-subscription',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiBillingSyncSubscriptionRoute =
  ApiBillingSyncSubscriptionRouteImport.update({
    id: '/api/billing/sync-subscription',
    path: '/api/billing/sync-subscription',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWebhooksRazorpayRoute = ApiWebhooksRazorpayRouteImport.update({
  id: '/api/webhooks/razorpay',
  path: '/api/webhooks/razorpay',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/batches': typeof AuthenticatedBatchesRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/fees': typeof AuthenticatedFeesRoute
  '/invites': typeof AuthenticatedInvitesRoute
  '/plan': typeof AuthenticatedPlanRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/students': typeof AuthenticatedStudentsRouteWithChildren
  '/join/$token': typeof JoinTokenRoute
  '/admin/subscriptions': typeof AuthenticatedAdminSubscriptionsRoute
  '/receipts/$paymentId': typeof AuthenticatedReceiptsPaymentIdRoute
  '/settings/team': typeof AuthenticatedSettingsTeamRoute
  '/students/$id': typeof AuthenticatedStudentsIdRoute
  '/api/billing/start-subscription': typeof ApiBillingStartSubscriptionRoute
  '/api/billing/sync-subscription': typeof ApiBillingSyncSubscriptionRoute
  '/api/webhooks/razorpay': typeof ApiWebhooksRazorpayRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/batches': typeof AuthenticatedBatchesRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/fees': typeof AuthenticatedFeesRoute
  '/invites': typeof AuthenticatedInvitesRoute
  '/plan': typeof AuthenticatedPlanRoute
  '/students': typeof AuthenticatedStudentsRouteWithChildren
  '/join/$token': typeof JoinTokenRoute
  '/admin/subscriptions': typeof AuthenticatedAdminSubscriptionsRoute
  '/receipts/$paymentId': typeof AuthenticatedReceiptsPaymentIdRoute
  '/settings/team': typeof AuthenticatedSettingsTeamRoute
  '/students/$id': typeof AuthenticatedStudentsIdRoute
  '/api/billing/start-subscription': typeof ApiBillingStartSubscriptionRoute
  '/api/billing/sync-subscription': typeof ApiBillingSyncSubscriptionRoute
  '/api/webhooks/razorpay': typeof ApiWebhooksRazorpayRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/attendance': typeof AuthenticatedAttendanceRoute
  '/_authenticated/batches': typeof AuthenticatedBatchesRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/fees': typeof AuthenticatedFeesRoute
  '/_authenticated/invites': typeof AuthenticatedInvitesRoute
  '/_authenticated/plan': typeof AuthenticatedPlanRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/_authenticated/students': typeof AuthenticatedStudentsRouteWithChildren
  '/join/$token': typeof JoinTokenRoute
  '/_authenticated/admin/subscriptions': typeof AuthenticatedAdminSubscriptionsRoute
  '/_authenticated/receipts/$paymentId': typeof AuthenticatedReceiptsPaymentIdRoute
  '/_authenticated/settings/team': typeof AuthenticatedSettingsTeamRoute
  '/_authenticated/students/$id': typeof AuthenticatedStudentsIdRoute
  '/api/billing/start-subscription': typeof ApiBillingStartSubscriptionRoute
  '/api/billing/sync-subscription': typeof ApiBillingSyncSubscriptionRoute
  '/api/webhooks/razorpay': typeof ApiWebhooksRazorpayRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/analytics'
    | '/attendance'
    | '/batches'
    | '/billing'
    | '/dashboard'
    | '/fees'
    | '/invites'
    | '/plan'
    | '/settings'
    | '/students'
    | '/join/$token'
    | '/admin/subscriptions'
    | '/receipts/$paymentId'
    | '/settings/team'
    | '/students/$id'
    | '/api/billing/start-subscription'
    | '/api/billing/sync-subscription'
    | '/api/webhooks/razorpay'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/analytics'
    | '/attendance'
    | '/batches'
    | '/billing'
    | '/dashboard'
    | '/fees'
    | '/invites'
    | '/plan'
    | '/students'
    | '/join/$token'
    | '/admin/subscriptions'
    | '/receipts/$paymentId'
    | '/settings/team'
    | '/students/$id'
    | '/api/billing/start-subscription'
    | '/api/billing/sync-subscription'
    | '/api/webhooks/razorpay'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/_authenticated/analytics'
    | '/_authenticated/attendance'
    | '/_authenticated/batches'
    | '/_authenticated/billing'
    | '/_authenticated/dashboard'
    | '/_authenticated/fees'
    | '/_authenticated/invites'
    | '/_authenticated/plan'
    | '/_authenticated/settings'
    | '/_authenticated/students'
    | '/join/$token'
    | '/_authenticated/admin/subscriptions'
    | '/_authenticated/receipts/$paymentId'
    | '/_authenticated/settings/team'
    | '/_authenticated/students/$id'
    | '/api/billing/start-subscription'
    | '/api/billing/sync-subscription'
    | '/api/webhooks/razorpay'
    | '/_authenticated/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  JoinTokenRoute: typeof JoinTokenRoute
  ApiBillingStartSubscriptionRoute: typeof ApiBillingStartSubscriptionRoute
  ApiBillingSyncSubscriptionRoute: typeof ApiBillingSyncSubscriptionRoute
  ApiWebhooksRazorpayRoute: typeof ApiWebhooksRazorpayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/attendance': {
      id: '/_authenticated/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AuthenticatedAttendanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/batches': {
      id: '/_authenticated/batches'
      path: '/batches'
      fullPath: '/batches'
      preLoaderRoute: typeof AuthenticatedBatchesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/fees': {
      id: '/_authenticated/fees'
      path: '/fees'
      fullPath: '/fees'
      preLoaderRoute: typeof AuthenticatedFeesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/invites': {
      id: '/_authenticated/invites'
      path: '/invites'
      fullPath: '/invites'
      preLoaderRoute: typeof AuthenticatedInvitesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/plan': {
      id: '/_authenticated/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof AuthenticatedPlanRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/students': {
      id: '/_authenticated/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AuthenticatedStudentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/join/$token': {
      id: '/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof JoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/subscriptions': {
      id: '/_authenticated/admin/subscriptions'
      path: '/admin/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AuthenticatedAdminSubscriptionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/receipts/$paymentId': {
      id: '/_authenticated/receipts/$paymentId'
      path: '/receipts/$paymentId'
      fullPath: '/receipts/$paymentId'
      preLoaderRoute: typeof AuthenticatedReceiptsPaymentIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/team': {
      id: '/_authenticated/settings/team'
      path: '/team'
      fullPath: '/settings/team'
      preLoaderRoute: typeof AuthenticatedSettingsTeamRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/students/$id': {
      id: '/_authenticated/students/$id'
      path: '/$id'
      fullPath: '/students/$id'
      preLoaderRoute: typeof AuthenticatedStudentsIdRouteImport
      parentRoute: typeof AuthenticatedStudentsRoute
    }
    '/api/billing/start-subscription': {
      id: '/api/billing/start-subscription'
      path: '/api/billing/start-subscription'
      fullPath: '/api/billing/start-subscription'
      preLoaderRoute: typeof ApiBillingStartSubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/sync-subscription': {
      id: '/api/billing/sync-subscription'
      path: '/api/billing/sync-subscription'
      fullPath: '/api/billing/sync-subscription'
      preLoaderRoute: typeof ApiBillingSyncSubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/razorpay': {
      id: '/api/webhooks/razorpay'
      path: '/api/webhooks/razorpay'
      fullPath: '/api/webhooks/razorpay'
      preLoaderRoute: typeof ApiWebhooksRazorpayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsTeamRoute: typeof AuthenticatedSettingsTeamRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsTeamRoute: AuthenticatedSettingsTeamRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedStudentsRouteChildren {
  AuthenticatedStudentsIdRoute: typeof AuthenticatedStudentsIdRoute
}

const AuthenticatedStudentsRouteChildren: AuthenticatedStudentsRouteChildren = {
  AuthenticatedStudentsIdRoute: AuthenticatedStudentsIdRoute,
}

const AuthenticatedStudentsRouteWithChildren =
  AuthenticatedStudentsRoute._addFileChildren(
    AuthenticatedStudentsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedAttendanceRoute: typeof AuthenticatedAttendanceRoute
  AuthenticatedBatchesRoute: typeof AuthenticatedBatchesRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFeesRoute: typeof AuthenticatedFeesRoute
  AuthenticatedInvitesRoute: typeof AuthenticatedInvitesRoute
  AuthenticatedPlanRoute: typeof AuthenticatedPlanRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedStudentsRoute: typeof AuthenticatedStudentsRouteWithChildren
  AuthenticatedAdminSubscriptionsRoute: typeof AuthenticatedAdminSubscriptionsRoute
  AuthenticatedReceiptsPaymentIdRoute: typeof AuthenticatedReceiptsPaymentIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedAttendanceRoute: AuthenticatedAttendanceRoute,
  AuthenticatedBatchesRoute: AuthenticatedBatchesRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFeesRoute: AuthenticatedFeesRoute,
  AuthenticatedInvitesRoute: AuthenticatedInvitesRoute,
  AuthenticatedPlanRoute: AuthenticatedPlanRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedStudentsRoute: AuthenticatedStudentsRouteWithChildren,
  AuthenticatedAdminSubscriptionsRoute: AuthenticatedAdminSubscriptionsRoute,
  AuthenticatedReceiptsPaymentIdRoute: AuthenticatedReceiptsPaymentIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  JoinTokenRoute: JoinTokenRoute,
  ApiBillingStartSubscriptionRoute: ApiBillingStartSubscriptionRoute,
  ApiBillingSyncSubscriptionRoute: ApiBillingSyncSubscriptionRoute,
  ApiWebhooksRazorpayRoute: ApiWebhooksRazorpayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
